language: csharp
mono: none
dotnet: 2.1.302
# Travis only supports Ubuntu 14 which has a very old openversion from 2014. 
# Updating the package was not possible due to a dependency error at postgres-client.
os: osx
script:
  - dotnet build src/Chaincode/Chaincode/Chaincode.csproj --configuration Release
  - dotnet test src/Chaincode/Chaincode.Test/Chaincode.Test.csproj --configuration Release
deploy:
  - provider: script
    script: bash .deploy.sh
    on:
      branch: master
  - provider: script
    script: bash .deploy.sh prerelease
    on:
      branch: develop